name: eis-ml
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib
  - numpy
  - seaborn
  - scipy
  - xgboost
  - scikit-learn
  - pandas
  - python=3.7
  - black
  - pip=21.2.2
  - pip:
    - tsfresh==0.19.0
